Open from clipboard
cassidyjames/ephemeral pull request #277
Opened 2021-03-10 19:28 UTC by meisenzahl

Sometimes I copy a link to the clipboard because it is not recognized as a link in the application. This pull request adds the action to open a link from the clipboard.

https://user-images.githubusercontent.com/10796736/110685942-18e0ae00-81df-11eb-909d-74e5c25310c0.mp4

2021-03-11 21:14 UTC, cassidyjames requested changes
Nice! Just a few copy/naming nits but otherwise this looks good.

2021-03-11 21:14 UTC, cassidyjames commented on data/launcher.desktop.in
> +Actions=New;Open From Clipboard;
```suggestion
Actions=New;Clipboard;
```

2021-03-11 21:14 UTC, cassidyjames commented on data/launcher.desktop.in
> +Name=Open From Clipboard
```suggestion
[Desktop Action Clipboard]
Name=Open from Clipboard
```

2021-03-11 21:14 UTC, cassidyjames commented on data/launcher.desktop.in
> +Exec=com.github.cassidyjames.ephemeral --open-from-clipboard
```suggestion
Exec=com.github.cassidyjames.ephemeral --clipboard
```

2021-03-11 21:14 UTC, cassidyjames commented on src/Application.vala
> +        { "open-from-clipboard", 'c', 0, OptionArg.NONE, ref open_from_clipboard,
```suggestion
        { "clipboard", 'c', 0, OptionArg.NONE, ref open_from_clipboard,
```

2021-03-15 17:39 UTC, cassidyjames approved these changes

2021-03-15 17:39 UTC, merged

2021-03-15 17:39 UTC, cassidyjames commented
Thanks!

2021-03-25 16:41 UTC, cassidyjames commented
@meisenzahl I had to revert this for now as it seemed to break opening links at all, and I didn't review it closely enough to understand why. :sweat_smile: I am still open to this feature, but I have to test it more thoroughly.

2021-03-30 09:40 UTC, meisenzahl commented
I'm really sorry for breaking the previous behavior.

> Note that this flag only affects the default implementation of local_command_line, and has no effect if g_application_handles_command_line is given.

https://valadoc.org/gio-2.0/GLib.ApplicationFlags.HANDLES_OPEN.html

I will try to fix this.